import React from 'react';

export default function QuoteForm() {
  return (
    <>
<section id="quote" className="section bg-light"><div className="container"><div className="section-header"><h2 className="section-title"><span className="lang-zh">获取报价</span><span className="lang-en">Get a Quote</span></h2><p className="section-desc"><span className="lang-zh">填写需求,我们将在 24 小时内回复。</span><span className="lang-en">Fill out the form and we will reply within 24 hours.</span></p></div><div className="quote-container"><form><div className="form-grid"><div className="form-group"><label className="form-label">Name / 姓名</label><input type="text" className="form-input" placeholder="Your Name" required="" /></div><div className="form-group"><label className="form-label">Contact / 联系方式 (Email/Phone)</label><input type="text" className="form-input" placeholder="Email or Phone" required="" /></div><div className="form-group"><label className="form-label">Service Type / 服务类型</label><select className="form-select"><option>Business Cards 名片</option><option>Flyers/Brochures 宣传单/折页</option><option>Signs/Banners 招牌/喷绘</option><option>Packaging 包装</option><option>Other 其他</option></select></div><div className="form-group"><label className="form-label">Quantity / 数量</label><input type="text" className="form-input" placeholder="e.g. 500" /></div><div className="form-group full-width"><label className="form-label">Project Details / 需求详情 (尺寸、纸张、工艺)</label><textarea className="form-textarea" rows="4" placeholder="例如:300g 铜版纸,双面覆哑膜,需要设计..."></textarea></div><div className="form-group full-width text-center" style={{marginTop: '20px'}}><button type="submit" className="btn btn-primary" style={{width: '200px'}}><span className="lang-zh">提交询价</span><span className="lang-en">Submit Request</span></button></div></div></form><div className="file-guide"><h4 style={{marginBottom: '15px', color: 'var(--primary-color)'}}><i className="fa-solid fa-file-circle-check"></i> Design & File Guide 文件指南</h4><div className="guide-grid"><div className="guide-item"><strong>Formats 格式</strong>PDF, AI, PSD, High-res JPG</div><div className="guide-item"><strong>Resolution 分辨率</strong>300dpi (Print), 150dpi (Large Format)</div><div className="guide-item"><strong>Bleed 出血</strong>3mm / 0.125" on all sides</div><div className="guide-item"><strong>Color 颜色</strong>CMYK Mode (Not RGB)</div></div></div></div></div></section>
    </>
  );
}
